export default  {
    products: [
       
        {id: 1,
            name: 'Reebok Instapump Fury CNCPTS Versace',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok1.jpg'
        },
        {id: 2,
            name: 'Reebok Instapump Fury Chromat Emerald',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok2.jpg'
        },
        {id: 3,
            name: 'Reebok Fury Chelsea Triple Black (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok3.jpg'
        },
        {id: 4,
            name: 'Reebok Instapump Fury OB Black White (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok4.jpg'
        },
        {id: 5,
            name: 'Reebok Instapump Fury OB Neon Cherry (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok5.jpg'
        },
        {id: 6,
            name: 'Reebok Instapump Fury OB Collegiate Navy',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok6.jpg'
        },
        {id: 7,
            name: 'Reebok Instapump Fury Scarlet Toxic Yellow',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok7.jpg'
        },
        {id: 8,
            name: 'Reebok Instapump Fury Cold Grey Collegiate Navy',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok8.jpg'
        },
        {id: 9,
            name: 'Reebok Instapump Fury White Excellent Red',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok9.jpg'
        },
        {id: 10,
            name: 'Reebok Instapump Fury Road Black',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok10.jpg'
        },
        {id: 11,
            name: 'Reebok Instapump Fury Major "Oxygen Mask"',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok11.jpg'
        },
    ]
}



