export default  {
    products: [
       
        {id: 1,
            name: 'New Balance 327 Concepts Cape',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance1.jpg'
        },
        {id: 2,
            name: 'New Balance 992 JJJJound Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance2.jpg'
        },
        {id: 3,
            name: 'New Balance 992 Yellow Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance3.jpg'
        },
        {id: 4,
            name: 'New Balance 992 Blue Teal Rose',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance4.jpg'
        },
        {id: 5,
            name: 'New Balance 992 Tan',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance5.jpg'
        },
        {id: 6,
            name: 'New Balance 992 Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance6.jpg'
        },
        {id: 7,
            name: 'New Balance 992 Multi-Color',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance7.jpg'
        },
        {id: 8,
            name: 'New Balance 998 Multi-Color',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance8.jpg'
        },
        {id: 9,
            name: 'New Balance 998 Burgundy Chalk',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance9.jpg'
        },
        {id: 10,
            name: 'New Balance 998 Grey Blue',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance10.jpg'
        },
        {id: 11,
            name: 'New Balance 998 Grey Light Blue Red',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance11.jpg'
        },
        {id: 12,
            name: 'New Balance 998 J. Crew Crater Lake',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance12.jpg'
        },
    ]
}



