export default  {
    products: [
       
        {id: 1,
            name: 'Converse Chuck Taylor All-Star 70s Ox Kith x Coca Cola Red',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse1.jpg'
        },
        {id: 2,
            name: 'Converse Chuck Taylor All-Star 70s Ox 7 Moncler Fragment Black',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse2.jpg'
        },
        {id: 3,
            name: 'Converse Chuck Taylor All-Star 70s Ox 7 Moncler Fragment White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse3.jpg'
        },
        {id: 4,
            name: 'Converse Chuck Taylor All-Star Ox Fragment Gold',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse4.jpg'
        },
        {id: 5,
            name: 'Converse Chuck Taylor All-Star Ox Optical White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse5.jpg'
        },
        {id: 6,
            name: 'Converse Chuck Taylor Ox Flag',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse6.jpg'
        },
        {id: 7,
            name: 'Converse Chuck Taylor OX Beach Glass',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse7.jpg'
        },
        {id: 8,
            name: 'Converse Chuck Taylor All-Star 70s Ox Black White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse8.jpg'
        },
        {id: 9,
            name: 'Converse Chuck Taylor All-Star 70s Ox Happy Camper Game Royal',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse9.jpg'
        },
        {id: 10,
            name: 'Converse Chuck Taylor All-Star 70s Ox Vince Staples Orange',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse9.jpg'
        },
    ]
}



