export default  {
    products: [
        {
            id: 1,
            name: 'Jordan 1 Retro High Satin Snake Chicago (W)',
            brand: 'NIKE',
            price: 4500,
            rating: 4.5,
            numStock: 100,
            numReview: 10,
            image: '/images/nike1.jpg'
        },
        {
            id: 2,
            name: 'Nike Air Max 97 Neon Seoul',
            brand: 'NIKE',
            price: 4800,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike2.jpg'
        },
        {
            id: 3,
            name: 'Nike Air Max 97 Black Blue Nebula',
            brand: 'NIKE',
            price: 4000,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike3.jpg'
        },
        {id: 4,
            name: 'Nike Air Force 1 Low Off-White Black White',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike4.jpg'
        },
        {id: 5,
            name: 'adidas Yeezy Boost 350 V2 Zebra',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas1.jpg'
        },
        {id: 6,
            name: 'adidas Yeezy Boost 350 V2 Cinder',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas2.jpg'
        },
        {id: 7,
            name: 'Jordan 1 Retro High Clay Green',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike6.jpg'
        },
        {id: 8,
            name: 'Jordan 1 Retro High Royal Toe',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/jordan1.jpg'
        },
        {id: 9,
            name: 'adidas Equipment Running Guidance Black',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas3.jpg'
        },
        {id: 10,
            name: 'Nike Air Force 1 Low Travis Scott Cactus Jack',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike5.jpg'
        },
        {id: 11,
            name: 'Puma RS-Dreamer J. Cole Black',
            brand: 'PUMA',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/puma1.jpg'
        },
        {id: 12,
            name: 'ASICS Gel-Lyte III Ronnie Fieg Militia (Special Box)',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics1.jpg'
        },
        {id: 13,
            name: 'Balenciaga Triple S Grey Red Blue (2018 Reissue)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Balenciaga1.jpg'
        },
        {id: 14,
            name: 'Converse Chuck Taylor All-Star 70s Ox Kith x Coca Cola Red',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse1.jpg'
        },
        {id: 15,
            name: 'New Balance 327 Concepts Cape',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance1.jpg'
        },
        {id: 16,
            name: 'Reebok Instapump Fury CNCPTS Versace',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok1.jpg'
        },
        {id: 17,
            name: 'adidas Yeezy Boost 350 V2 Beluga 2.0',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas4.jpg'
        },
        {id: 18,
            name: 'adidas Yeezy Boost 350 V2 Cinder',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas5.jpg'
        },
        {id: 19,
            name: 'adidas Yeezy Boost 350 V2 Semi Frozen Yellow',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas6.jpg'
        },
        {id: 20,
            name: 'adidas Yeezy 500 Soft Vision',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas7.jpg'
        },
        {id: 21,
            name: 'adidas Nite Jogger Beyonce Ivy Park',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas8.jpg'
        },
        {id: 22,
            name: 'adidas Sleek Super 72 Beyonce Ivy Park (W)',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas9.jpg'
        },
        {id: 23,
            name: 'adidas NMD XR1 OG Black',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas10.jpg'
        },
        {id: 24,
            name: 'adidas NMD Hu Pharrell Solar Pack Orange',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas11.jpg'
        },
        {id: 25,
            name: 'adidas Nite Jogger 3M Navy',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas12.jpg'
        },
        {id: 26,
            name: 'adidas Nite Jogger 3M Core Black Crystal White',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/adidas13.jpg'
        },
        {id: 27,
            name: 'Nike Air Force 1 Low Travis Scott Cactus Jack',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike5.jpg'
        },
        {id: 28,
            name: 'Nike Blazer Mid 77 Vintage White Black',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike7.jpg'
        },
        {id: 29,
            name: 'Nike Dunk Low Off-White University Red',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike8.jpg'
        },
        {id: 30,
            name: 'Nike Dunk Low SP Kentucky (2020)',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike9.jpg'
        },
        {id: 31,
            name: 'Nike Dunk Low Viotech (2019)',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike10.jpg'
        },
        {id: 32,
            name: 'Nike Air Fear Of God Moccasin Black',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike11.jpg'
        },
        {id: 33,
            name: 'Vans Sk8-Hi Odd Future Donut',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/vans2.jpg'
        },
        {id: 34,
            name: 'Vans Old Skool WTAPS Black Orange',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans4.jpg'
        },
        {id: 35,
            name: 'Vans Old Skool Red Dahlia',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans5.jpg'
        },
        {id: 36,
            name: 'Vans Old Skool Dark Cheddar',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans6.jpg'
        },
        {id: 37,
            name: 'Vans Old Skool Ultramarine',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans7.jpg'
        },
        {id: 38,
            name: 'Vans Old Skool Black White',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans8.jpg'
        },
        {id: 39,
            name: 'Vans Old Skool Woodland Camo',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans9.jpg'
        },
        {id: 40,
            name: 'Vans Old Skool KENZO Floral Green',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans10.jpg'
        },
        {id: 41,
            name: 'Vans Old Skool KENZO Floral Yellow',
            brand: 'VANS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/vans11.jpg'
        },
        {id: 42,
            name: 'Converse Chuck Taylor All-Star 70s Ox 7 Moncler Fragment Black',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse2.jpg'
        },
        {id: 43,
            name: 'Converse Chuck Taylor All-Star 70s Ox 7 Moncler Fragment White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse3.jpg'
        },
        {id: 44,
            name: 'Converse Chuck Taylor All-Star Ox Fragment Gold',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse4.jpg'
        },
        {id: 45,
            name: 'Converse Chuck Taylor All-Star Ox Optical White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse5.jpg'
        },
        {id: 46,
            name: 'Converse Chuck Taylor Ox Flag',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse6.jpg'
        },
        {id: 47,
            name: 'Converse Chuck Taylor OX Beach Glass',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse7.jpg'
        },
        {id: 48,
            name: 'Converse Chuck Taylor All-Star 70s Ox Black White',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse8.jpg'
        },
        {id: 49,
            name: 'Converse Chuck Taylor All-Star 70s Ox Happy Camper Game Royal',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse9.jpg'
        },
        {id: 50,
            name: 'Balenciaga Triple S Black White Red (2018 Reissue)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 5,
            numReview: 20, 
            image: '/images/Balenciaga2.jpg'
        },
        {id: 51,
            name: 'Balenciaga Triple S Neon Yellow (2018 Reissue)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 20,
            numReview: 20, 
            image: '/images/Balenciaga3.jpg'
        },
        {id: 52,
            name: 'Balenciaga Triple S White (2018 Reissue)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/Balenciaga4.jpg'
        },
        {id: 53,
            name: 'Balenciaga Triple S Triple Black (2018 Reissue) (Nondistressed)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/Balenciaga5.jpg'
        },
        {id: 54,
            name: 'Balenciaga Triple S Beige',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/Balenciaga6.jpg'
        },
        {id: 55,
            name: 'Balenciaga Triple S Pink',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/Balenciaga7.jpg'
        },
        {id: 56,
            name: 'Balenciaga Triple S Grey Red',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 10,
            numReview: 20, 
            image: '/images/Balenciaga8.jpg'
        },
        {id: 57,
            name: 'Reebok Instapump Fury Chromat Emerald',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok2.jpg'
        },
        {id: 58,
            name: 'Reebok Fury Chelsea Triple Black (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok3.jpg'
        },
        {id: 59,
            name: 'Reebok Instapump Fury OB Black White (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok4.jpg'
        },
        {id: 60,
            name: 'Reebok Instapump Fury OB Neon Cherry (W)',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok5.jpg'
        },
        {id: 61,
            name: 'Reebok Instapump Fury OB Collegiate Navy',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok6.jpg'
        },
        {id: 62,
            name: 'Reebok Instapump Fury Scarlet Toxic Yellow',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok7.jpg'
        },
        {id: 63,
            name: 'Reebok Instapump Fury Cold Grey Collegiate Navy',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok8.jpg'
        },
        {id: 64,
            name: 'Reebok Instapump Fury White Excellent Red',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok9.jpg'
        },
        {id: 65,
            name: 'Reebok Instapump Fury Road Black',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok10.jpg'
        },
        {id: 66,
            name: 'Reebok Instapump Fury Major "Oxygen Mask"',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok11.jpg'
        },
        {id: 67,
            name: 'New Balance 992 JJJJound Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance2.jpg'
        },
        {id: 68,
            name: 'New Balance 992 Yellow Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance3.jpg'
        },
        {id: 69,
            name: 'New Balance 992 Blue Teal Rose',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance4.jpg'
        },
        {id: 70,
            name: 'New Balance 992 Tan',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance5.jpg'
        },
        {id: 71,
            name: 'New Balance 992 Grey',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance6.jpg'
        },
        {id: 72,
            name: 'New Balance 992 Multi-Color',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance7.jpg'
        },
        {id: 73,
            name: 'New Balance 998 Multi-Color',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance8.jpg'
        },
        {id: 74,
            name: 'New Balance 998 Burgundy Chalk',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance9.jpg'
        },
        {id: 75,
            name: 'New Balance 998 Grey Blue',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance10.jpg'
        },
        {id: 76,
            name: 'New Balance 998 Grey Light Blue Red',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance11.jpg'
        },
        {id: 77,
            name: 'New Balance 998 J. Crew Crater Lake',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance12.jpg'
        },
        {id: 78,
            name: 'ASICS Gel-Lyte III Afew "Koi" (Regular Box)',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics2.jpg'
        },
        {id: 79,
            name: 'ASICS Gel-Lyte III Purple Grey Lime',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics3.jpg'
        },
        {id: 80,
            name: 'Asics Gel-Lyte III White Piedmont Grey',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics4.jpg'
        },
        {id: 81,
            name: 'Asics Gel-Lyte III Lime Zest',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics5.jpg'
        },
        {id: 82,
            name: 'ASICS Gel-Lyte III Russet Brown',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics6.jpg'
        },
        {id: 83,
            name: 'Asics Gel-Lyte III Dragon Fruit',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics7.jpg'
        },
        {id: 84,
            name: 'Asics Gel-Lyte III Techno Cyan',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics8.jpg'
        },
        {id: 85,
            name: 'ASICS Gel-Lyte III Ivory',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics9.jpg'
        },
        {id: 86,
            name: 'Asics Gel-Lyte III Aquarium',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics10.jpg'
        },
    ]
}



